#!/usr/bin/env node

const fs = require('fs')
const { Command } = require('commander')
const program = new Command()

program.command('create')
  .description('create a new template')
  .argument('<name>')
  .action((dir) => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir)
    } else {
      console.log(`directory <${dir}> has already exit`)
    }
  })
program.parse(process.argv)